spring:
  datasource:
    url: jdbc:postgresql:${DB_NAME}
    username: ${DB_USER}
    password: ${DB_USER_PASS}
  jackson:
    serialization:
      # So we get dd-mm-yy instead of [dd,mm,yy] for LocalDate
      write_dates_as_timestamps: false

logging:
  level:
    pro.absolutne: trace

management:
  security:
    enabled: false
