spring:
  jackson:
    serialization:
      # So we get dd-mm-yy instead of [dd,mm,yy] for LocalDate
      write_dates_as_timestamps: false

logging:
  level:
    pro.absolutne: trace
    org.hibernate: trace

management:
  security:
    enabled: false
