version: 2
jobs:
  build:
    working_directory: ~/lunchagator-server
    docker:
      - image: openjdk:8
    steps:
      - checkout
      - run: ./gradlew build
#      - save_cache:
#          paths:
#            - ~/.m2
#          key: {{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/libs/lunchagator-server-0.0.1-SNAPSHOT.jar
          destination: das-app.jar