version: 2
jobs:
  build:
    working_directory: ~/lunchagator-server
    docker:
      - image: openjdk:8
    steps:
      - checkout
      - restore_cache:
          key: '{{ checksum "build.gradle" }}'
      - run: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: '{{ checksum "build.gradle" }}'
      - store_artifacts:
          path: build/libs/lunchagator-server.jar
          destination: das-app.jar
      - setup_remote_docker
      - run:
         name: install Docker client
         command: |
           set -x
           VER="17.03.0-ce"
           curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
           tar -xz -C /tmp -f /tmp/docker-$VER.tgz
           mv /tmp/docker/* /usr/bin
      - run: |
         TAG=0.1.$CIRCLE_BUILD_NUM
         NAME=abspro/lunchgator-server
         docker build -t $NAME .
         docker tag $NAME $NAME:$TAG
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker push $NAME
