version: 2
jobs:
  build:
    working_directory: ~/lunchagator-server
    docker:
      - image: openjdk:8
    steps:
      - checkout
      - run: ./gradlew build
#      - save_cache:
#          paths:
#            - ~/.m2
#          key: {{ checksum "build.gradle" }}
      - store_artifacts:
        path: build/libs/lunchgator-server-*.jar
        destination: das-app.jar