version: 2
jobs:
  build:
    working_directory: ~/lunchagator-server
    docker:
      - image: openjdk:8
    steps:
      - checkout
      - run: ./gradlew build
#      - save_cache:
#          paths:
#            - ~/.m2
#          key: {{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/libs/lunchagator-server-0.0.1-SNAPSHOT.jar
          destination: das-app.jar
      - setup_remote_docker
      - run:
          TAG=0.1.$CIRCLE_BUILD_NUM
          NAME=test:$TAG
          docker build -t $NAME
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $NAME
